api_platform:
    title: HappyVisio API
    version: 1.0.0
    show_webby: false
    enable_entrypoint: false
    enable_docs: false
    enable_swagger: false
    enable_swagger_ui: false
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header