version: "3"

services:
  database:
    image: mysql:latest
    container_name: happyvisio_database
    restart: always
    volumes:
      - happyvisio-db-data:/var/lib/mysql
      - ./.docker/mysql/dump:/home/dump:rw
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hv
      MYSQL_PASSWORD: hv
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    networks:
      - happyvisio_network

  phpmyadmin:
    image: phpmyadmin
    container_name: happyvisio_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - 8880:80
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 3000000000
    networks:
      - happyvisio_network

  happyvisio:
    build:
      context: .
      dockerfile: .docker/hv/Dockerfile
    container_name: happyvisio_www
    ports:
      - 8881:80
      - 8443:443
    volumes:
      - ./.docker/apache:/etc/apache2/sites-available/ssl
      - ./.docker/hv/000-default.conf:/etc/apache2/sites-availabale/ssl
      - ./:/var/www/html
    networks:
      - happyvisio_network

networks:
  happyvisio_network:

volumes:
  happyvisio-db-data: